version: '3.4'

services:
  webapi:
    environment:
      APICLEAN_CONN: Host=db-postgres;Port=5432;Database=ApiClean;User Id=postgres;Password=password;
    ports:
      - "5000:80"
    networks:
      - apicleanarchitecture-network

  db-postgres:
    image: postgres
    container_name: db-postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    networks:
      - apicleanarchitecture-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes: 
      - "./pgadmin:/root/.pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    ports:
      - "${PGADMIN_PORT:-15432}:80"
    depends_on:
      - db-postgres
    networks:
      - apicleanarchitecture-network

volumes:
  db_volume:
 
networks: 
  apicleanarchitecture-network: