version: '3.7'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    networks:
      - apicleanarchitecture-network

networks: 
  apicleanarchitecture-network:
